### ISSUE TITLE
Questions for class meeting Wednesday 31/3

### ISSUE THREAD

**Issue by iandurbach** [iandurbach/exploratory-data-analysis#4]
Please leave any question that you'd like answered during the class meeting here. This can be about ANYTHING --  about any of material covered so far -- spatial data, version control, principles -- or about the assignment, or about anything at all. Anything we don't get time to cover in class I'll make a short video about. 

If your question related to an exercise, please include details of anything you'd tried -- that'll be helpful to others who may be having the same issues you are.

**Comment by anilaaryan** [comment]
Ian, While doing UTM reprojection of the lat and long points and taking Euclidian distance between the projected points, in the lecture you specified Zone 48 and datum=WGS84. where can we get this standard std lat_long file with the zone information?

**Comment by iandurbach** [comment]
@anilaaryan there's a Datasets folder under Resources with the lat-long csv in it, have also put it in the Lesson now.

**Comment by anilaaryan** [comment]
Thank you Ian. Got it.

**Comment by CailinPerrie** [comment]
Hi Ian, on Wednesday, please can we go through the question that asks us to change the axis text of the plot so that it does not include numbers in scientific notation? I am not sure if I am just missing something in my code but would appreciate a quick run through of the different ways to do this :)

**Comment by anilaaryan** [comment]
Hi Ian, What is the difference between reading data normally and reading data with quarter degree grid cells?

**Comment by RSwallow987** [comment]
I also couldn't download the data mentioned in Chaoter 13 exercises - It keeps on saying it has a network error. I then tried to download it independently of R but it won't let me unzip it due to the same issue. Is anyone else experiencing this ?

**Comment by CailinPerrie** [comment]
Hi Ian, I am struggling to install the brolgar package. I am getting the following error "package ‘brolgar’ is not available for this version of R". Any suggestions?

**Comment by iandurbach** [comment]
@YPerumal -- good question, will discuss in class, but just to say I've added a document on command line git in the Lecture 11/12 folder (on Vula and here)

**Comment by iandurbach** [comment]
@CailinPerrie, its not on CRAN, but you can install it from the package developer's github repo.
```
library(remotes)
remotes::install_github("njtierney/brolgar")
```
Being able to instal non-CRAN packages from GitHub this easily is super useful -- means you can write your own small R package, and you or others can install it as above.

**Comment by liamcarew** [comment]
1)	EDA PRINCIPLES:

https://github.com/liamcarew/exploratory-data-analysis/blob/master/goodpractice/goodpractice-exercises.R 

a)	In terms of creating smoother or rougher histograms/frequency polygons, would this only require using different bin widths? Is the way that I have tried to change smoothness/roughness of the plots correct? (lines 39-102)

b)	struggling to add fill to plot – I have been able to use colour to distinguish the lines but when using fill, I keep getting stacked graphs when I want unstacked filled line graphs (unless that is correct?)(lines 136-158)

c)	Is the way that I have discretised my continuous variables correct? Or is there a better way to do this (lines 215-239)

d)	I am struggling to convert my values on the x-axis bins from scientific to exponent notation (lines 432-443)

2)	SPATIAL DATA:

https://github.com/liamcarew/exploratory-data-analysis/blob/master/spatial-data/class-exercise.R

a)	Struggling to plot 'Predom_Age' properly where the ages are shown - For the first question of the exercise, it seems that it contains missing values and the age ranges given were character strings. Would you recommend to deal with the missing values by imputation of the mode or remove the values? Or am I approaching the question wrong?

b)	Struggling to answer the second question in the exercise where you have to fill each grid by number of settlements - I've been able to plot the grid but struggling with shading by number of settlements. Any help would be much appreciated.

c)	Is the reasoning behind not converting the quarter-degree grid cells to lat-long format using st_transform() because the .shp file doesn’t require lat-long format to plot? Seem to get the grid cells regardless of whether I change them to lat-long format or not. 

d)	Ch 13 of Geocomputation in R exercises <- I have gone through the chapter but just struggling with the exercises at the end.

3)	TIME SERIES:

a)	Can you plot an ordinal categorical variable like 'month' (TS slides - slide 37) on the x-axis or must it always be numeric since the numeric variables that are used for indexing (like 'weeks') in TS must have a natural ordering?

**Comment by CailinPerrie** [comment]
> @CailinPerrie, its not on CRAN, but you can install it from the package developer's github repo.
> 
> ```
> library(remotes)
> remotes::install_github("njtierney/brolgar")
> ```
> 
> Being able to instal non-CRAN packages from GitHub this easily is super useful -- means you can write your own small R package, and you or others can install it as above.

Hi Ian, 
I did try and install it this way as well, and it bugs me out completely. Shuts down my R and everything. Do you know why this could be happening?
