### ISSUE TITLE
Questions for class meeting 7th April

### ISSUE THREAD

**Issue by iandurbach** [iandurbach/exploratory-data-analysis#6]
Please leave any question that you'd like answered during the class meeting here. This class meeting is primarily about the lectures covering Shiny apps and interactive and animated graphics, but your question can be about ANYTHING -- about any of material covered so far, the assignment, or about anything at all. Anything we don't get time to cover in class I'll make a short video about.

If your question related to an exercise, please include details of anything you'd tried -- that'll be helpful to others who may be having the same issues you are.

**Comment by CailinPerrie** [comment]
Hi Ian, please could you upload the recording for the meeting on April 1st? I was unfortunately unable to attend and would like to catch up what I missed before this afternoons call.

**Comment by liamcarew** [comment]
Interactive Plots/Animations:

1. How could one add something like a geom_label at a particular transition/frame to highlight certain point(s) in that frame? (i.e. when Oceania is shown for the GDP per capita plot from Gapminder, to add a geom_label to say 'smallest number of observations'  to the frame when Oceania is shown or something like that)
2. For exercise 1, how could one add the grey background and narrower spacing of grid lines to the plot? (apologies if this is a stupid question - I struggled to find out how to do this online) 

A note for exercise 3: install and load 'gifski' and 'transformr' packages before running the animations otherwise you get a hundred (or more if you are lucky) .png files

**Comment by iandurbach** [comment]
@CailinPerrie these are up now, sorry for the wait.
@liamcarew, for 1 see the extra example in the folder for that lecture, for 2 try

```
plot_ly(diamonds, x = ~cut, color = I("red")) %>% layout(plot_bgcolor='lightgray') 
plot_ly(diamonds, x = ~cut, color = I("red")) %>% add_histogram() %>% layout(yaxis = list(dtick = 1000))
```

The options are all specified using the "layout" function, see here for some examples:
https://plotly.com/r/axes/
https://plotly.com/r/reference/#Layout_and_layout_style_objects
